"""
Bactomata data-processing helpers.

These functions operate on a parsed Bactomata experiment object, typically
loaded from a PKL generated by bactomata.parser.
"""

from __future__ import annotations

from typing import Iterable, List, Sequence, Tuple

import pandas as pd


def list_conditions(experiment: dict) -> pd.DataFrame:
    """
    Return the unique media + bacteria combinations present in the experiment.
    """

    data = experiment["data"]

    conditions = (
        data[["media_key", "bacteria_key"]]
        .drop_duplicates()
        .sort_values(["media_key", "bacteria_key"])
        .reset_index(drop=True)
    )

    return conditions


def get_growth_data(
    experiment: dict,
    media_key: str,
    bacteria_key: str,
    signal: str = "OD630",
    value_col: str = "value",
    include_well_info: bool = True,
) -> pd.DataFrame:
    """
    Extract time-series data for one media + bacteria condition.

    Replicate wells are kept as separate observations.
    """

    data = experiment["data"]

    selected = data[
        (data["media_key"] == media_key)
        & (data["bacteria_key"] == bacteria_key)
        & (data["signal"] == signal)
    ].copy()

    if selected.empty:
        raise ValueError(
            f"No data found for media_key={media_key}, "
            f"bacteria_key={bacteria_key}, signal={signal}"
        )

    keep_cols = [
        "expeID",
        "plate_id",
        "time_hhmmss",
        "time",
        "well",
        "signal",
        value_col,
        "media_key",
        "bacteria_key",
    ]

    if include_well_info:
        keep_cols.extend(["row", "column"])

    keep_cols = [col for col in keep_cols if col in selected.columns]

    selected = selected[keep_cols]
    selected = selected.rename(columns={value_col: signal})
    selected = selected.sort_values(["well", "time"]).reset_index(drop=True)

    return selected


def get_growth_matrix(
    experiment: dict,
    media_key: str,
    bacteria_key: str,
    signal: str = "OD630",
) -> pd.DataFrame:
    """
    Extract growth data as a time x replicate-well matrix.

    Each replicate well becomes one column.
    """

    growth = get_growth_data(
        experiment=experiment,
        media_key=media_key,
        bacteria_key=bacteria_key,
        signal=signal,
    )

    matrix = growth.pivot_table(
        index=["time", "time_hhmmss"],
        columns="well",
        values=signal,
    ).reset_index()

    matrix = matrix.sort_values("time").reset_index(drop=True)

    return matrix


def summarize_growth_data(
    experiment: dict,
    media_key: str,
    bacteria_key: str,
    signal: str = "OD630",
) -> pd.DataFrame:
    """
    Return mean, standard deviation, and replicate count over wells.
    """

    growth = get_growth_data(
        experiment=experiment,
        media_key=media_key,
        bacteria_key=bacteria_key,
        signal=signal,
    )

    summary = (
        growth.groupby(["time", "time_hhmmss"], as_index=False)
        .agg(
            mean=(signal, "mean"),
            std=(signal, "std"),
            n=(signal, "count"),
        )
        .sort_values("time")
        .reset_index(drop=True)
    )

    return summary


def infer_plate_dimensions(experiment: dict) -> tuple[list[str], int, int]:
    """
    Infer plate row labels and number of columns from well_annotations.
    """

    well_annotations = experiment["well_annotations"].copy()

    row_labels = sorted(well_annotations["row"].astype(str).unique())
    n_rows = len(row_labels)
    n_cols = int(well_annotations["column"].max())

    return row_labels, n_rows, n_cols


def get_endpoint_values_per_well(
    experiment: dict,
    signal: str = "OD630",
    endpoint_time: str = "last",
    value_col: str = "value",
) -> pd.DataFrame:
    """
    Return one value per well for a given signal.

    For kinetic data, endpoint_time can be "first" or "last".
    """

    data = experiment["data"].copy()
    data = data[data["signal"] == signal].copy()

    if data.empty:
        raise ValueError(f"No data found for signal={signal}")

    data = data.sort_values(["well", "time"])

    if endpoint_time == "last":
        endpoint = data.groupby("well", as_index=False).tail(1).copy()
    elif endpoint_time == "first":
        endpoint = data.groupby("well", as_index=False).head(1).copy()
    else:
        raise ValueError("endpoint_time must be 'first' or 'last'")

    endpoint = endpoint[["well", "time", "time_hhmmss", value_col]].copy()
    endpoint = endpoint.rename(columns={value_col: "endpoint_value"})

    return endpoint


def get_well_data(
    experiment: dict,
    well: str,
    signal: str = "OD630",
    value_col: str = "value",
) -> pd.DataFrame:
    """
    Extract data for a single well and signal.
    """

    data = experiment["data"].copy()

    selected = data[(data["well"] == well) & (data["signal"] == signal)].copy()

    if selected.empty:
        raise ValueError(f"No data found for well={well}, signal={signal}")

    selected = selected.sort_values("time").reset_index(drop=True)

    return selected


def get_wells_for_condition(
    experiment: dict,
    media_key: str,
    bacteria_key: str,
) -> list[str]:
    """
    Return all wells matching a given media + bacteria condition.
    """

    well_annotations = experiment["well_annotations"].copy()

    selected = well_annotations[
        (well_annotations["media_key"] == media_key)
        & (well_annotations["bacteria_key"] == bacteria_key)
    ].copy()

    wells = selected["well"].tolist()

    return wells
